[package]
org = "ballerinax"
name = "kafka"
version = "4.2.1"
authors = ["Ballerina"]
keywords = ["kafka", "event streaming", "network", "messaging"]
repository = "https://github.com/ballerina-platform/module-ballerinax-kafka"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.10.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "kafka-native"
version = "4.2.1"
path = "../native/build/libs/kafka-native-4.2.1-SNAPSHOT.jar"

[[platform.java17.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka-clients"
version = "3.5.1"
path = "./lib/kafka-clients-3.5.1.jar"

[[platform.java17.dependency]]
groupId = "org.apache.kafka"
artifactId = "kafka_2.12"
version = "3.5.1"
path = "./lib/kafka_2.12-3.5.1.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.5.0"
path = "./lib/constraint-native-1.5.0.jar"

[build-options]
observabilityIncluded=true
